import product1 from "assests/product-1-cropped-removebg-preview.png";
import brand from "assests/cat-image.jpg";
const productsData = [
  {
    id: 1,
    cat: "Yokohama",
    name: "GEOLANDAR - AT/G015",
    catImage: brand,
    image: product1,
    type: "WINTER",
    price: "80$",
    carType: "Passenger cars / minivan",
  },
  {
    id: 1,
    cat: "Yokohama",
    name: "GEOLANDAR - AT/G015",
    catImage: brand,
    image: product1,
    type: "WINTER",
    price: "80$",
    carType: "Passenger cars / minivan",
  },
  {
    id: 1,
    cat: "Yokohama",
    name: "GEOLANDAR - AT/G015",
    catImage: brand,
    image: product1,
    type: "WINTER",
    price: "80$",
    carType: "Passenger cars / minivan",
  },
  {
    id: 1,
    cat: "Yokohama",
    name: "GEOLANDAR - AT/G015",
    catImage: brand,
    image: product1,
    type: "WINTER",
    price: "80$",
    carType: "Passenger cars / minivan",
  },
  {
    id: 1,
    cat: "Yokohama",
    name: "GEOLANDAR - AT/G015",
    catImage: brand,
    image: product1,
    type: "WINTER",
    price: "80$",
    carType: "Passenger cars / minivan",
  },
  {
    id: 1,
    cat: "Yokohama",
    name: "GEOLANDAR - AT/G015",
    catImage: brand,
    image: product1,
    type: "WINTER",
    price: "80$",
    carType: "Passenger cars / minivan",
  },
  {
    id: 1,
    cat: "Yokohama",
    name: "GEOLANDAR - AT/G015",
    catImage: brand,
    image: product1,
    type: "WINTER",
    price: "80$",
    carType: "Passenger cars / minivan",
  },
];

export default productsData;
